package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"

	"github.com/Swejal08/go-ggqlen/graph/model"
)

// CreateEventMembership is the resolver for the createEventMembership field.
func (r *mutationResolver) CreateEventMembership(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: CreateEventMembership - createEventMembership"))
}

// AssignEventMembership is the resolver for the assignEventMembership field.
func (r *mutationResolver) AssignEventMembership(ctx context.Context, input model.AssignEventMembership) (*string, error) {
	panic(fmt.Errorf("not implemented: AssignEventMembership - assignEventMembership"))
}
