package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"

	accessControl "github.com/Swejal08/go-ggqlen/access-control"
	"github.com/Swejal08/go-ggqlen/enums"
	"github.com/Swejal08/go-ggqlen/graph/model"
	"github.com/Swejal08/go-ggqlen/graph/services"
)

// AssignEventMembership is the resolver for the assignEventMembership field.
func (r *mutationResolver) AssignEventMembership(ctx context.Context, input model.AssignEventMembership) (*string, error) {
	userId := ctx.Value("userId").(string)

	var err error

	allowedRoles := []enums.EventMembershipRole{enums.Admin, enums.Contributor}

	accessError := accessControl.Check(allowedRoles, userId, input.EventID)

	if accessError != nil {
		return nil, accessError
	}

	membership, err := services.GetEventMembership(input.EventID, userId)

	if string(membership.Role) == enums.GetRoleDescription(int(enums.Contributor)) && input.Role != model.Role(enums.GetRoleDescription(int(enums.Attendee))) {
		return nil, fmt.Errorf("Contributor can only invite Attendees")
	}

	eventMembership, err := services.GetEventMembership(input.EventID, input.UserID)

	if err != nil {
		return nil, err
	}

	if eventMembership == nil {
		err = services.CreateEventMembership(input.EventID, input.UserID, input.Role)

	} else {
		err = services.UpdateEventMembership(input, eventMembership)
	}

	successMessage := "Event Membership has been assigned"
	return &successMessage, nil
}

// RemoveEventMembership is the resolver for the removeEventMembership field.
func (r *mutationResolver) RemoveEventMembership(ctx context.Context, input model.RemoveEventMembership) (*string, error) {
	userId := ctx.Value("userId").(string)

	allowedRoles := []enums.EventMembershipRole{enums.Admin}

	accessError := accessControl.Check(allowedRoles, userId, input.EventID)

	if accessError != nil {
		return nil, accessError
	}

	err := services.RemoveEventMembership(input)

	if err != nil {
		return nil, err
	}

	successMessage := "Event Membership has been removed"
	return &successMessage, nil
}
