// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type AssignEventMembership struct {
	EventID int  `json:"eventId" validate:"required"`
	UserID  int  `json:"userId" validate:"required"`
	Role    Role `json:"role" validate:"required"`
}

type Category struct {
	ID           string `json:"id"`
	CategoryName string `json:"categoryName"`
}

type CategoryExpense struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Expense int    `json:"expense"`
}

type DeleteCategory struct {
	EventID int    `json:"eventId" validate:"required"`
	ID      string `json:"id" validate:"required"`
}

type DeleteEvent struct {
	ID string `json:"id" validate:"required"`
}

type DeleteExpense struct {
	ID      string `json:"id" validate:"required"`
	EventID int    `json:"eventId" validate:"required"`
}

type Event struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Location    string `json:"location"`
	StartDate   string `json:"startDate"`
	EndDate     string `json:"endDate"`
}

type EventMembership struct {
	ID      string `json:"id"`
	EventID int    `json:"eventId"`
	UserID  int    `json:"userId"`
	Role    Role   `json:"role"`
}

type Expense struct {
	ID          string    `json:"id"`
	EventID     int       `json:"eventId"`
	ItemName    string    `json:"itemName"`
	Cost        int       `json:"cost"`
	Description *string   `json:"description,omitempty"`
	CategoryID  *Category `json:"categoryId,omitempty"`
}

type NewCategory struct {
	EventID      int    `json:"eventId" validate:"required"`
	CategoryName string `json:"categoryName" validate:"required"`
}

type NewEvent struct {
	Name        string `json:"name" validate:"required"`
	Description string `json:"description" validate:"required"`
	Location    string `json:"location" validate:"required"`
	StartDate   string `json:"startDate" validate:"required"`
	EndDate     string `json:"endDate" validate:"required"`
}

type NewExpense struct {
	EventID     int     `json:"eventId" validate:"required"`
	ItemName    string  `json:"itemName" validate:"required"`
	Cost        int     `json:"cost" validate:"required,int"`
	Description *string `json:"description,omitempty"`
	CategoryID  int     `json:"categoryId" validate:"required"`
}

type NewUser struct {
	Name  string  `json:"name" validate:"required"`
	Email string  `json:"email" validate:"required,email"`
	Phone *string `json:"phone,omitempty"`
}

type RemoveEventMembership struct {
	EventID int `json:"eventId" validate:"required"`
	UserID  int `json:"userId" validate:"required"`
}

type TotalExpense struct {
	TotalExpense int                `json:"totalExpense"`
	Name         string             `json:"name"`
	Category     []*CategoryExpense `json:"category"`
}

type UpdateCategory struct {
	ID           string  `json:"id" validate:"required"`
	EventID      int     `json:"eventId" validate:"required"`
	CategoryName *string `json:"categoryName,omitempty" validate:"required"`
}

type UpdateEvent struct {
	ID          string  `json:"id" validate:"required"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Location    *string `json:"location,omitempty"`
	StartDate   *string `json:"startDate,omitempty" validate:"date"`
	EndDate     *string `json:"endDate,omitempty" validate:"date"`
}

type UpdateExpense struct {
	ID          string  `json:"id" validate:"required"`
	EventID     int     `json:"eventId" validate:"required"`
	ItemName    *string `json:"itemName,omitempty"`
	Cost        *int    `json:"cost,omitempty" validate:"int"`
	Description *string `json:"description,omitempty"`
	CategoryID  *int    `json:"categoryId,omitempty"`
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Email string  `json:"email"`
	Phone *string `json:"phone,omitempty"`
}

type Role string

const (
	RoleContributor Role = "contributor"
	RoleAdmin       Role = "admin"
	RoleAttendee    Role = "attendee"
)

var AllRole = []Role{
	RoleContributor,
	RoleAdmin,
	RoleAttendee,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleContributor, RoleAdmin, RoleAttendee:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
